import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faUser,
  faBars,
  faMagnifyingGlass,
  faHouse,
  faBriefcase,
  faFilm,
  faImage,
  faGlobe,
  faHeart,
  faFlask,
  faPersonRunning,
  faMicrochip,
  faAngleLeft,
  faAngleRight,
  faCircleNotch,
  faCircle as faCircleSolid,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faFrown,
} from '@fortawesome/free-solid-svg-icons'

import { faCircle, faBookmark } from '@fortawesome/free-regular-svg-icons'

library.add(
  faUser,
  faBars,
  faMagnifyingGlass,
  faHouse,
  faBriefcase,
  faFilm,
  faImage,
  faGlobe,
  faHeart,
  faFlask,
  faPersonRunning,
  faMicrochip,
  faAngleLeft,
  faAngleRight,
  faCircleNotch,
  faCircleSolid,
  faCircle,
  faBookmark,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faFrown,
)
